//LOGIN
export const LOGIN_REQUST = "LOGIN_REQUST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOGOUT
export const LOGOUT_REQUST = "LOGOUT_REQUST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//USER LOADING
export const USER_LOADING_REQUST = "USER_LOADING_REQUST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

//CLEAR ERR
export const CLEAR_ERROR_REQUST = "CLEAR_ERROR_REQUST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

//LOGOUT
export const REGISTER_REQUST = "REGISTER_REQUST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//POST WRITE
export const POST_WRITE_REQUST = "POST_WRITE_REQUST";
export const POST_WRITE_SUCCESS = "POST_WRITE_SUCCESS";
export const POST_WRITE_FAILURE = "POST_WRITE_FAILURE";

//POST WRITE
export const POST_LOADING_REQUST = "POST_LOADING_REQUST";
export const POST_LOADINGE_SUCCESS = "POST_LOADING_SUCCESS";
export const POST_LOADING_FAILURE = "POST_LOADING_FAILURE";

// POST UPLOAD
export const POST_UPLOADING_REQUEST = "POST_UPLOADING_REQUEST";
export const POST_UPLOADING_FAILURE = "POST_UPLOADING_FAILURE";
export const POST_UPLOADING_SUCCESS = "POST_UPLOADING_SUCCESS";

// POST Detail Loading
export const POST_DETAIL_LOADING_REQUEST = "POST_DETAIL_LOADING_REQUEST";
export const POST_DETAIL_LOADING_FAILURE = "POST_DETAIL_LOADING_FAILURE";
export const POST_DETAIL_LOADING_SUCCESS = "POST_DETAIL_LOADING_SUCCESS";

// POST DELETE
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";

// POST EDIT Loaindg
export const POST_EDIT_LOADING_REQUEST = "POST_EDIT_LOADING_REQUEST";
export const POST_EDIT_LOADING_FAILURE = "POST_EDIT_LOADING_FAILURE";
export const POST_EDIT_LOADING_SUCCESS = "POST_EDIT_LOADING_SUCCESS";

// POST EDIT upLoaindg
export const POST_EDIT_UPLOADING_REQUEST = "POST_EDIT_UPLOADING_REQUEST";
export const POST_EDIT_UPLOADING_FAILURE = "POST_EDIT_UPLOADING_FAILURE";
export const POST_EDIT_UPLOADING_SUCCESS = "POST_EDIT_UPLOADING_SUCCESS";

//Comment loading
export const COMMENT_LOADING_REQUEST = "COMMENT_LOADING_REQUEST";
export const COMMENT_LOADING_FAILURE = "COMMENT_LOADING_FAILURE";
export const COMMENT_LOADING_SUCCESS = "COMMENT_LOADING_SUCCESS";

//Comment uploading
export const COMMENT_UPLOADING_REQUEST = "COMMENT_UPLOADING_REQUEST";
export const COMMENT_UPLOADING_FAILURE = "COMMENT_UPLOADING_FAILURE";
export const COMMENT_UPLOADING_SUCCESS = "COMMENT_UPLOADING_SUCCESS"; //

//category Find
export const CATEGORY_FIND_REQUEST = "CATEGORY_FIND_REQUEST";
export const CATEGORY_FIND_FAILURE = "CATEGORY_FIND_FAILURE";
export const CATEGORY_FIND_SUCCESS = "CATEGORY_FIND_SUCCESS";

//search Find
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";

//User profile
export const USER_PROFILE_LOADING_REQUEST = "USER_PROFILE_LOADING_REQUEST";
export const USER_PROFILE_LOADING_SUCCESS = "USER_PROFILE_LOADING_SUCCESS";
export const USER_PROFILE_LOADING_FAILURE = "USER_PROFILE_LOADING_FAILURE";

//User name edit
export const USER_NAME_EDIT_REQUEST = "USER_NAME_EDIT_REQUEST";
export const USER_NAME_EDIT_SUCCESS = "USER_NAME_EDIT_SUCCESS";
export const USER_NAME_EDIT_FAILURE = "USER_NAME_EDIT_FAILURE";

//User name edit
export const USER_EMAIL_EDIT_REQUEST = "USER_EMAIL_EDIT_REQUEST";
export const USER_EMAIL_EDIT_SUCCESS = "USER_EMAIL_EDIT_SUCCESS";
export const USER_EMAIL_EDIT_FAILURE = "USER_EMAIL_EDIT_FAILURE";

//User name edit
export const USER_PASSWORD_EDIT_REQUEST = "USER_PASSWORD_EDIT_REQUEST";
export const USER_PASSWORD_EDIT_SUCCESS = "USER_PASSWORD_EDIT_SUCCESS";
export const USER_PASSWORD_EDIT_FAILURE = "USER_PASSWORD_EDIT_FAILURE";

//User proflie_Url edit
export const USER_PROFILEURL_EDIT_REQUEST = "USER_PROFILEURL_EDIT_REQUEST";
export const USER_PROFILEURL_EDIT_SUCCESS = "USER_PROFILEURL_EDIT_SUCCESS";
export const USER_PROFILEURL_EDIT_FAILURE = "USER_PROFILEURL_EDIT_FAILURE";

//User proflie_Url delete
export const USER_PROFILEURL_DELETE_REQUEST = "USER_PROFILEURL_DELETE_REQUEST";
export const USER_PROFILEURL_DELETE_SUCCESS = "USER_PROFILEURL_DELETE_SUCCESS";
export const USER_PROFILEURL_DELETE_FAILURE = "USER_PROFILEURL_DELETE_FAILURE";

//User delete
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";

//User profile seasrch
export const USER_PROFILE_SEARCH_REQUEST = "USER_PROFILE_SEARCH_REQUEST";
export const USER_PROFILE_SEARCH_SUCCESS = "USER_PROFILE_SEARCH_SUCCESS";
export const USER_PROFILE_SEARCH_FAILURE = "USER_PROFILE_SEARCH_FAILURE";
