//LOGIN
export const LOGIN_REQUST = "LOGIN_REQUST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOGOUT
export const LOGOUT_REQUST = "LOGOUT_REQUST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//USER LOADING
export const USER_LOADING_REQUST = "USER_LOADING_REQUST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

//CLEAR ERR
export const CLEAR_ERROR_REQUST = "CLEAR_ERROR_REQUST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

//LOGOUT
export const REGISTER_REQUST = "REGISTER_REQUST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//POST WRITE
export const POST_WRITE_REQUST = "POST_WRITE_REQUST";
export const POST_WRITE_SUCCESS = "POST_WRITE_SUCCESS";
export const POST_WRITE_FAILURE = "POST_WRITE_FAILURE";

//POST WRITE
export const POST_LOADING_REQUST = "POST_LOADING_REQUST";
export const POST_LOADINGE_SUCCESS = "POST_LOADING_SUCCESS";
export const POST_LOADING_FAILURE = "POST_LOADING_FAILURE";
