//LOGIN
export const LOGIN_REQUST = "LOGIN_REQUST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOGOUT
export const LOGOUT_REQUST = "LOGOUT_REQUST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//USER LOADING
export const USER_LOADING_REQUST = "USER_LOADING_REQUST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

//CLEAR ERR
export const CLEAR_ERROR_REQUST = "CLEAR_ERROR_REQUST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

//LOGOUT
export const REGISTER_REQUST = "REGISTER_REQUST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//POST WRITE
export const POST_WRITE_REQUST = "POST_WRITE_REQUST";
export const POST_WRITE_SUCCESS = "POST_WRITE_SUCCESS";
export const POST_WRITE_FAILURE = "POST_WRITE_FAILURE";

//POST WRITE
export const POST_LOADING_REQUST = "POST_LOADING_REQUST";
export const POST_LOADINGE_SUCCESS = "POST_LOADING_SUCCESS";
export const POST_LOADING_FAILURE = "POST_LOADING_FAILURE";

// POST UPLOAD
export const POST_UPLOADING_REQUEST = "POST_UPLOADING_REQUEST";
export const POST_UPLOADING_FAILURE = "POST_UPLOADING_FAILURE";
export const POST_UPLOADING_SUCCESS = "POST_UPLOADING_SUCCESS";

// POST Detail Loading
export const POST_DETAIL_LOADING_REQUEST = "POST_DETAIL_LOADING_REQUEST";
export const POST_DETAIL_LOADING_FAILURE = "POST_DETAIL_LOADING_FAILURE";
export const POST_DETAIL_LOADING_SUCCESS = "POST_DETAIL_LOADING_SUCCESS";

// POST DELETE
export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_FAILURE = "POST_DELETE_FAILURE";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";

// POST EDIT Loaindg
export const POST_EDIT_LOADING_REQUEST = "POST_EDIT_LOADING_REQUEST";
export const POST_EDIT_LOADING_FAILURE = "POST_EDIT_LOADING_FAILURE";
export const POST_EDIT_LOADING_SUCCESS = "POST_EDIT_LOADING_SUCCESS";

// POST EDIT upLoaindg
export const POST_EDIT_UPLOADING_REQUEST = "POST_EDIT_UPLOADING_REQUEST";
export const POST_EDIT_UPLOADING_FAILURE = "POST_EDIT_UPLOADING_FAILURE";
export const POST_EDIT_UPLOADING_SUCCESS = "POST_EDIT_UPLOADING_SUCCESS";

//Comment loading
export const COMMENT_LOADING_REQUEST = "COMMENT_LOADING_REQUEST";
export const COMMENT_LOADING_FAILURE = "COMMENT_LOADING_FAILURE";
export const COMMENT_LOADING_SUCCESS = "COMMENT_LOADING_SUCCESS";

//Comment uploading
export const COMMENT_UPLOADING_REQUEST = "COMMENT_UPLOADING_REQUEST";
export const COMMENT_UPLOADING_FAILURE = "COMMENT_UPLOADING_FAILURE";
export const COMMENT_UPLOADING_SUCCESS = "COMMENT_UPLOADING_SUCCESS";
